---
- hosts: all
  become: true

  tasks:
    - name: Stop the running docker
      shell: docker stop pst_client
    - name: Remove the docker
      shell: docker rm -f pst_client
    - name: Remove image of the docker
      shell: docker image rm -f saravansrg/pst_client:latest

    - name: Download the latest docker and run
      shell: docker run -d -p 2000:2000 --name pst_client saravansrg/pst_client:latest

